Repository timescale/docs, pull requests merged in 2022-11, with the labels that each got.

#1757 fix(link check)
  _code-samples/toolkit/gauge_agg.md
  _code-samples/toolkit/stats_agg-two-variables.md
  mlc_config.json
  timescaledb/how-to-guides/hyperfunctions/stats-aggs.md
  timescaledb/tutorials/analyze-bitcoin-blockchain/analyze-blockchain.md
Labels: bug

#1748 feat(data tiering): add docs
  _partials/_cloud-data-tiering-beta.md
  _partials/_experimental-private-beta.md
  api/attach_tablespace.md
  api/detach_tablespace.md
  api/detach_tablespaces.md
  api/move_chunk.md
  cloud/data-tiering/index.md
  cloud/data-tiering/tier-data-object-storage.md
  cloud/page-index/page-index.js
  timescaledb/how-to-guides/page-index/page-index.js
  timescaledb/how-to-guides/schema-management/manage-storage.md
  timescaledb/how-to-guides/user-defined-actions/example-tiered-storage.md
  timescaledb/how-to-guides/user-defined-actions/index.md
  timescaledb/overview/core-concepts/chunks.md
  timescaledb/overview/release-notes/index.md
Labels: documentation, enhancement, launch

#1774 fix(stats_agg): fix formatting
  api/_hyperfunctions/stats_agg-one-variable/kurtosis.md
  api/_hyperfunctions/stats_agg-one-variable/num_vals.md
  api/_hyperfunctions/stats_agg-one-variable/skewness.md
  api/_hyperfunctions/stats_agg-one-variable/stddev.md
  api/_hyperfunctions/stats_agg-one-variable/variance.md
  api/_hyperfunctions/stats_agg-two-variables/kurtosis_y_x.md
  api/_hyperfunctions/stats_agg-two-variables/num_vals.md
  api/_hyperfunctions/stats_agg-two-variables/skewness_y_x.md
  api/_hyperfunctions/stats_agg-two-variables/stats_agg.md
  api/_hyperfunctions/stats_agg-two-variables/stddev_y_x.md
  api/_hyperfunctions/stats_agg-two-variables/variance_y_x.md
Labels: bug, documentation

#1776 fix(links): remove broken link
  timescaledb/overview/release-notes/index.md
Labels: bug, documentation

#1758 Reorganize financial functions and add candlestick functions
  api/_hyperfunctions/candlestick_agg/candlestick.md
  api/_hyperfunctions/candlestick_agg/candlestick_agg.md
  api/_hyperfunctions/candlestick_agg/close.md
  api/_hyperfunctions/candlestick_agg/close_time.md
  api/_hyperfunctions/candlestick_agg/examples.md
  api/_hyperfunctions/candlestick_agg/high.md
  api/_hyperfunctions/candlestick_agg/high_time.md
  api/_hyperfunctions/candlestick_agg/intro.md
  api/_hyperfunctions/candlestick_agg/low.md
  api/_hyperfunctions/candlestick_agg/low_time.md
  api/_hyperfunctions/candlestick_agg/open.md
  api/_hyperfunctions/candlestick_agg/open_time.md
  api/_hyperfunctions/candlestick_agg/rollup.md
  api/_hyperfunctions/candlestick_agg/volume.md
  api/_hyperfunctions/candlestick_agg/vwap.md
  api/_hyperfunctions/ohlc/close.md
  api/_hyperfunctions/ohlc/close_time.md
  api/_hyperfunctions/ohlc/examples.md
  api/_hyperfunctions/ohlc/high.md
  api/_hyperfunctions/ohlc/high_time.md
  api/_hyperfunctions/ohlc/intro.md
  api/_hyperfunctions/ohlc/low.md
  api/_hyperfunctions/ohlc/low_time.md
  api/_hyperfunctions/ohlc/ohlc.md
  api/_hyperfunctions/ohlc/open.md
  api/_hyperfunctions/ohlc/open_time.md
  api/_hyperfunctions/ohlc/rollup.md
  api/financial-analysis.md
  api/ohlc.md
  api/open-high-low-close-time.md
  api/open-high-low-close.md
  api/page-index/page-index.js
Labels: documentation, enhancement

#1756 feat(cloud 2.0): all updates for Cloud 2.0
  .data/redirects.json
  cloud/cloud-multi-node.md
  cloud/integrations.md
  cloud/members/members-list.md
  cloud/page-index/page-index.js
  cloud/postgresql-extensions.md
  cloud/service-operations/database-parameters/advanced-parameters.md
  cloud/service-operations/database-parameters/customize-configuration.md
  cloud/service-operations/database-parameters/index.md
  cloud/service-operations/service-management.md
  cloud/service-settings/index.md
Labels: cloud-2.0

#1697 Update service creation for Promscale steps
  _partials/_cloud-create-service-promscale.md
Labels: promscale

#1799 reorg(percentile approximation): migrate to new hyperfunctions template
  _tutorials/deprecated.json
  api/_hyperfunctions/tdigest/approx_percentile.md
  api/_hyperfunctions/tdigest/approx_percentile_rank.md
  api/_hyperfunctions/tdigest/examples.md
  api/_hyperfunctions/tdigest/intro.md
  api/_hyperfunctions/tdigest/max_val
  api/_hyperfunctions/tdigest/mean.md
  api/_hyperfunctions/tdigest/min_val
  api/_hyperfunctions/tdigest/num_vals.md
  api/_hyperfunctions/tdigest/rollup.md
  api/_hyperfunctions/tdigest/tdigest.md
  api/_hyperfunctions/uddsketch/approx_percentile.md
  api/_hyperfunctions/uddsketch/approx_percentile_rank.md
  api/_hyperfunctions/uddsketch/error.md
  api/_hyperfunctions/uddsketch/examples.md
  api/_hyperfunctions/uddsketch/intro.md
  api/_hyperfunctions/uddsketch/mean.md
  api/_hyperfunctions/uddsketch/num_vals.md
  api/_hyperfunctions/uddsketch/percentile_agg.md
  api/_hyperfunctions/uddsketch/rollup.md
  api/_hyperfunctions/uddsketch/uddsketch.md
  api/approx_percentile.md
  api/approx_percentile_rank.md
  api/error.md
  api/max_val.md
  api/mean.md
  api/min_val.md
  api/num_vals-percentile.md
  api/page-index/page-index.js
  api/percentile-aggregation-methods.md
  api/percentile-approximation.md
  api/percentile_agg.md
  api/rollup-percentile.md
  api/tdigest.md
  api/uddsketch.md
Labels: documentation
