Repository timescale/docs, pull requests merged in 2024-01, with the labels that each got.

#2889 docs: add docs about project ownership transfer
  use-timescale/members/index.md
  use-timescale/members/members-list.md
  use-timescale/members/project-ownership.md
  use-timescale/page-index/page-index.js
Labels: documentation

#2952 Update stats-aggs.md
  use-timescale/hyperfunctions/stats-aggs.md
Labels: docs-update-needed

#2959 Explain how encryption works in cloud
  use-timescale/security/strict-ssl.md
Labels: documentation, invalid
